"""Adapter-layer contracts shared by every P4-A source-family adapter."""

from seven_lens.sources.adapters.transport import (
    EXECUTOR_WIRE_CONTRACT,
    ExecutorRequest,
    ExecutorResponse,
    FamilyNotExecutableError,
    FetchResult,
    InvalidEndpointError,
    InvalidParameterError,
    PolicyGetTransport,
    PreparedRequest,
    SourceAuditSink,
    SourceContentTypeError,
    SourceFetchAudit,
    SourceFetchRedirectError,
    SourceFetchTimeoutError,
    SourceGetExecutor,
    SourceMalformedResponseError,
    SourceRequestError,
    SourceStatusError,
    SourceTransportBudgetError,
)

__all__ = [
    "EXECUTOR_WIRE_CONTRACT",
    "ExecutorRequest",
    "ExecutorResponse",
    "FamilyNotExecutableError",
    "FetchResult",
    "InvalidEndpointError",
    "InvalidParameterError",
    "PolicyGetTransport",
    "PreparedRequest",
    "SourceAuditSink",
    "SourceContentTypeError",
    "SourceFetchAudit",
    "SourceFetchRedirectError",
    "SourceFetchTimeoutError",
    "SourceGetExecutor",
    "SourceMalformedResponseError",
    "SourceRequestError",
    "SourceStatusError",
    "SourceTransportBudgetError",
]
